<template>
  <div>

  <router-view></router-view>
  </div>
</template>


<style>
  
details > summary {
list-style: none;
}
details > summary::-webkit-details-marker {
display: none;
}

    details summary::-webkit-details-marker {
    display: none;
    }
    .text-outline{
        text-shadow: 2px 0px 0px rgba(255, 0, 132, 1), 0px 2px 0px rgba(255, 0, 132, 1),0px -2px 0px rgba(255, 0, 132, 1), -2px 0px 0px rgba(255, 0, 132, 1);
        
    }



/* ----------------------------------------------
 * Generated by Animista on 2022-9-16 18:5:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-horizontal-bottom
 * ----------------------------------------
 */
*{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}











  </style>