<template>
  <div>
    <!-- <router-view v-slot="{Component}" >
  <transition name="fade" mode="out-in">
    <Component :is="Component"/>

  </transition>
  </router-view> -->
  <router-view></router-view>
  </div>
</template>


<style>
  .fade-enter-from,
  .fade-leave-to{opacity: 0;}
  
  .fade-enter-active,
  .fade-1eave-active{transition : opacity 0.5s ease-out;}


  
details > summary {
list-style: none;
}
details > summary::-webkit-details-marker {
display: none;
}

    details summary::-webkit-details-marker {
    display: none;
    }
    .text-outline{
        text-shadow: 2px 0px 0px rgba(255, 0, 132, 1), 0px 2px 0px rgba(255, 0, 132, 1),0px -2px 0px rgba(255, 0, 132, 1), -2px 0px 0px rgba(255, 0, 132, 1);
        
    }



    .shine {
	-webkit-animation: shine 4000ms cubic-bezier(0.680, -0.550, 0.265, 1.550) infinite alternate both;
	        animation: shine 4000ms cubic-bezier(0.680, -0.550, 0.265, 1.550) infinite alternate both;
        }

/* ----------------------------------------------
 * Generated by Animista on 2022-9-16 18:5:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-horizontal-bottom
 * ----------------------------------------
 */
 @-webkit-keyframes shine {
  0% {

  }
  100% {
    text-shadow: #FFF 0px 0px 5px, #FFF 0px 0px 10px, #FFF 0px 0px 15px, #FF2D95 0px 0px 20px, #FF2D95 0px 0px 30px, #FF2D95 0px 0px 40px, #FF2D95 0px 0px 50px, #FF2D95 0px 0px 75px;
    color: rgb(255, 124, 216);
  }
}
@keyframes shine {
  0% {

  }
  100% {

    text-shadow: #FFF 0px 0px 5px, #FFF 0px 0px 10px, #FFF 0px 0px 15px, #FF2D95 0px 0px 20px, #FF2D95 0px 0px 30px, #FF2D95 0px 0px 40px, #FF2D95 0px 0px 50px, #FF2D95 0px 0px 75px;
    color: rgb(255, 124, 216);
  }
}
*{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}











  </style>